/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    'mock-outbox': MockOutbox;
    producers: Producer;
    wines: Wine;
    vintages: Vintage;
    packaging: Packaging;
    'card-designs': CardDesign;
    orders: Order;
    'checkout-drafts': CheckoutDraft;
    'payload-kv': PayloadKv;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'mock-outbox': MockOutboxSelect<false> | MockOutboxSelect<true>;
    producers: ProducersSelect<false> | ProducersSelect<true>;
    wines: WinesSelect<false> | WinesSelect<true>;
    vintages: VintagesSelect<false> | VintagesSelect<true>;
    packaging: PackagingSelect<false> | PackagingSelect<true>;
    'card-designs': CardDesignsSelect<false> | CardDesignsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'checkout-drafts': CheckoutDraftsSelect<false> | CheckoutDraftsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('vi' | 'en') | ('vi' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'vi' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Buyer accounts. Read-only here; accounts are made and changed on the storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name?: string | null;
  phone?: string | null;
  address?: string | null;
  consents: {
    terms: boolean;
    privacy: boolean;
    at: string;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * Pre-launch mock: account mail is written here and sent nowhere. Read-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mock-outbox".
 */
export interface MockOutbox {
  id: number;
  to: string;
  subject: string;
  body: string;
  sentAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "producers".
 */
export interface Producer {
  id: number;
  name: string;
  country: 'FR' | 'IT' | 'ES' | 'PT' | 'DE' | 'AT' | 'US' | 'CL' | 'AR' | 'AU' | 'NZ' | 'ZA';
  region: string;
  story: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wines".
 */
export interface Wine {
  id: number;
  /**
   * Shared by both locales: /ruou-vang/<slug> and /en/ruou-vang/<slug>.
   */
  slug: string;
  producer: number | Producer;
  name: string;
  type: 'red' | 'white' | 'rose' | 'sparkling' | 'sweet';
  country: 'FR' | 'IT' | 'ES' | 'PT' | 'DE' | 'AT' | 'US' | 'CL' | 'AR' | 'AU' | 'NZ' | 'ZA';
  region: string;
  appellation?: string | null;
  grapes: {
    grape: string;
    pct?: number | null;
    id?: string | null;
  }[];
  tasting: {
    nose: string;
    palate: string;
    finish: string;
  };
  /**
   * Each axis from 1 (low) to 5 (high).
   */
  profile: {
    body: number;
    tannin: number;
    sweetness: number;
    acidity: number;
  };
  pairings?:
    | (
        | 'beef'
        | 'pork'
        | 'poultry'
        | 'seafood'
        | 'fish'
        | 'cheese'
        | 'spicy'
        | 'dessert'
        | 'bun-cha'
        | 'pho'
        | 'bo-luc-lac'
        | 'goi-cuon'
        | 'cha-gio'
        | 'vit-quay'
      )[]
    | null;
  servingTempC: number;
  occasions?: ('gift' | 'tet' | 'celebration' | 'dinner' | 'everyday')[] | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vintages".
 */
export interface Vintage {
  id: number;
  wine: number | Wine;
  /**
   * Leave empty for a non-vintage (NV) wine.
   */
  year?: number | null;
  bottleMl: '375' | '750' | '1500';
  /**
   * % vol.
   */
  abvPct: number;
  /**
   * Law 44/2019 Art. 5.7 and 5.9. Derived from ABV; never stored.
   */
  adRestricted?: boolean | null;
  /**
   * Whole VND, VAT included.
   */
  priceVnd: number;
  stock: number;
  drinkFrom?: number | null;
  drinkTo?: number | null;
  importer: string;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packaging".
 */
export interface Packaging {
  id: number;
  code: string;
  name: string;
  description: string;
  /**
   * Bottles per unit.
   */
  capacity: number;
  /**
   * Bottle sizes (ml) it takes.
   */
  fits: ('375' | '750' | '1500')[];
  /**
   * Per unit, whole VND, VAT included. At least 1.
   */
  priceVnd: number;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "card-designs".
 */
export interface CardDesign {
  id: number;
  code: string;
  name: string;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Orders are never deleted. Only the status can be changed here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  number: string;
  status:
    | 'placed'
    | 'paid'
    | 'packed'
    | 'out_for_delivery'
    | 'delivered'
    | 'id_check_failed'
    | 'cancelled'
    | 'returned'
    | 'expired';
  token: string;
  clientKey: string;
  paymentDueAt: string;
  buyer: {
    name: string;
    phone: string;
    email: string;
    address: string;
  };
  customer?: (number | null) | Customer;
  ageAttestedAt: string;
  /**
   * Self: to the buyer at the buyer's address. Gift: to the recipient, who must be 18 or over and show ID.
   */
  delivery: {
    zone: 'hcmc' | 'hanoi';
    mode: 'self' | 'gift';
    recipient?: {
      name?: string | null;
      phone?: string | null;
      address?: string | null;
    };
    /**
     * YYYY-MM-DD, Asia/Ho_Chi_Minh.
     */
    date: string;
    window: 'morning' | 'afternoon' | 'evening';
  };
  /**
   * Packaging for any order; card, message, sender and hide prices for a gift.
   */
  gift?: {
    /**
     * Empty: no packaging.
     */
    packagingCode?: string | null;
    packagingNameVi?: string | null;
    packagingNameEn?: string | null;
    packagingUnits?: number | null;
    packagingUnitPriceVnd?: number | null;
    cardCode?: string | null;
    cardNameVi?: string | null;
    cardNameEn?: string | null;
    /**
     * Plain text, NFC, at most 250 code points.
     */
    message?: string | null;
    sender?: string | null;
    anonymous?: boolean | null;
    /**
     * Packing instruction: no price or receipt in the parcel.
     */
    hidePrices?: boolean | null;
  };
  lines: {
    vintage: number | Vintage;
    wineNameVi: string;
    wineNameEn: string;
    /**
     * Empty for NV.
     */
    year?: number | null;
    bottleMl: '375' | '750' | '1500';
    abvPct: number;
    unitPriceVnd: number;
    qty: number;
    id?: string | null;
  }[];
  /**
   * Whole VND, VAT included.
   */
  totals: {
    goodsVnd: number;
    wrapVnd: number;
    shippingVnd: number;
    vatIncludedVnd: number;
    totalVnd: number;
  };
  consents: {
    terms: boolean;
    privacy: boolean;
    at: string;
  };
  /**
   * Mock payment only: no provider, no card or account number.
   */
  payment: {
    method?: ('vietqr_mock' | 'card_mock') | null;
    status: 'unpaid' | 'failed' | 'paid';
    paidAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkout-drafts".
 */
export interface CheckoutDraft {
  id: number;
  handle: string;
  clientKey: string;
  expiresAt: string;
  buyer?: {
    name?: string | null;
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  attestedAt?: string | null;
  delivery?: {
    zone?: ('hcmc' | 'hanoi') | null;
    mode?: ('self' | 'gift') | null;
    recipient?: {
      name?: string | null;
      phone?: string | null;
      address?: string | null;
    };
    date?: string | null;
    window?: ('morning' | 'afternoon' | 'evening') | null;
  };
  gift?: {
    saved?: boolean | null;
    packaging?: string | null;
    card?: string | null;
    message?: string | null;
    sender?: string | null;
    hidePrices?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  address?: T;
  consents?:
    | T
    | {
        terms?: T;
        privacy?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mock-outbox_select".
 */
export interface MockOutboxSelect<T extends boolean = true> {
  to?: T;
  subject?: T;
  body?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "producers_select".
 */
export interface ProducersSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  region?: T;
  story?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wines_select".
 */
export interface WinesSelect<T extends boolean = true> {
  slug?: T;
  producer?: T;
  name?: T;
  type?: T;
  country?: T;
  region?: T;
  appellation?: T;
  grapes?:
    | T
    | {
        grape?: T;
        pct?: T;
        id?: T;
      };
  tasting?:
    | T
    | {
        nose?: T;
        palate?: T;
        finish?: T;
      };
  profile?:
    | T
    | {
        body?: T;
        tannin?: T;
        sweetness?: T;
        acidity?: T;
      };
  pairings?: T;
  servingTempC?: T;
  occasions?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vintages_select".
 */
export interface VintagesSelect<T extends boolean = true> {
  wine?: T;
  year?: T;
  bottleMl?: T;
  abvPct?: T;
  adRestricted?: T;
  priceVnd?: T;
  stock?: T;
  drinkFrom?: T;
  drinkTo?: T;
  importer?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packaging_select".
 */
export interface PackagingSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  description?: T;
  capacity?: T;
  fits?: T;
  priceVnd?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "card-designs_select".
 */
export interface CardDesignsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  number?: T;
  status?: T;
  token?: T;
  clientKey?: T;
  paymentDueAt?: T;
  buyer?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        address?: T;
      };
  customer?: T;
  ageAttestedAt?: T;
  delivery?:
    | T
    | {
        zone?: T;
        mode?: T;
        recipient?:
          | T
          | {
              name?: T;
              phone?: T;
              address?: T;
            };
        date?: T;
        window?: T;
      };
  gift?:
    | T
    | {
        packagingCode?: T;
        packagingNameVi?: T;
        packagingNameEn?: T;
        packagingUnits?: T;
        packagingUnitPriceVnd?: T;
        cardCode?: T;
        cardNameVi?: T;
        cardNameEn?: T;
        message?: T;
        sender?: T;
        anonymous?: T;
        hidePrices?: T;
      };
  lines?:
    | T
    | {
        vintage?: T;
        wineNameVi?: T;
        wineNameEn?: T;
        year?: T;
        bottleMl?: T;
        abvPct?: T;
        unitPriceVnd?: T;
        qty?: T;
        id?: T;
      };
  totals?:
    | T
    | {
        goodsVnd?: T;
        wrapVnd?: T;
        shippingVnd?: T;
        vatIncludedVnd?: T;
        totalVnd?: T;
      };
  consents?:
    | T
    | {
        terms?: T;
        privacy?: T;
        at?: T;
      };
  payment?:
    | T
    | {
        method?: T;
        status?: T;
        paidAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkout-drafts_select".
 */
export interface CheckoutDraftsSelect<T extends boolean = true> {
  handle?: T;
  clientKey?: T;
  expiresAt?: T;
  buyer?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        address?: T;
      };
  attestedAt?: T;
  delivery?:
    | T
    | {
        zone?: T;
        mode?: T;
        recipient?:
          | T
          | {
              name?: T;
              phone?: T;
              address?: T;
            };
        date?: T;
        window?: T;
      };
  gift?:
    | T
    | {
        saved?: T;
        packaging?: T;
        card?: T;
        message?: T;
        sender?: T;
        hidePrices?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  owner: {
    legalName: string;
    headOffice: string;
    legalRepresentative: string;
    businessRegistration: {
      number: string;
      date: string;
      place: string;
    };
    alcoholLicence: {
      number: string;
      issuer: string;
      date: string;
    };
    contactEmail: string;
    contactPhone: string;
    notificationLink?: string | null;
  };
  /**
   * Delivery zones, their flat fee (whole VND, VAT included) and lead days (the earliest delivery date is today + lead days).
   */
  zones?:
    | {
        zone: 'hcmc' | 'hanoi';
        feeVnd: number;
        leadDays: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Dates with no delivery (for example a Tết cut-off), as YYYY-MM-DD on the Vietnamese calendar.
   */
  blackoutDates?:
    | {
        date: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  owner?:
    | T
    | {
        legalName?: T;
        headOffice?: T;
        legalRepresentative?: T;
        businessRegistration?:
          | T
          | {
              number?: T;
              date?: T;
              place?: T;
            };
        alcoholLicence?:
          | T
          | {
              number?: T;
              issuer?: T;
              date?: T;
            };
        contactEmail?: T;
        contactPhone?: T;
        notificationLink?: T;
      };
  zones?:
    | T
    | {
        zone?: T;
        feeVnd?: T;
        leadDays?: T;
        id?: T;
      };
  blackoutDates?:
    | T
    | {
        date?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}